---
#- name: gather facts
#  setup: 


- name: apt-get update
  raw: apt-get update -qq

- name: install python 2.7 and aptitude
  raw: apt-get install -qq python2.7 aptitude python-apt python3-apt




#- name: Perform Safe Upgrade
#  apt: upgrade=safe update_cache=yes

- import_tasks: hostname.yml
- import_tasks: locale.yml
- import_tasks: limits.yml
- import_tasks: repo.yml
- import_tasks: packages.yml

