---
- name: Add deployment user
  user:
    name: "{{ deploy_user }}"
    password: "{{ deploy_password }}"
    shell: /bin/bash
    create_home: yes
  register: user_exist

- name: Create the user's key directory
  file:
    path: "/home/{{ deploy_user }}/.ssh"
    owner: "{{ deploy_user }}"
    state: directory
    mode: 0755


- name: Copy user SSH key
  copy:
    src: public_keys/id_rsa
    dest: "/home/{{ deploy_user }}/.ssh/id_rsa"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0600

- name: Add authorized deploy keys
  authorized_key:
    user: "{{ deploy_user }}"
    key: '{{ item }}'
  with_file:
     - public_keys/deploy_workstation.pub
     - public_keys/jumpserver_root.pub
     - public_keys/jumpserver_webuser.pub

- name: Remove sudo group rights
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    state: absent

- name: Add deploy user to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ deploy_user }} ALL"
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present


- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart sshd
